name: Run Tests
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update 
        sudo apt-get install --yes libgl1-mesa-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      if: always()
      run: |
        python -m pytest -x -v
